#!/bin/bash
export Dotfiles=~/Dotfiles

# Make ~/Dotfiles (And ~/Dotfiles.bak if there was an older one)
sudo cp -a $Dotfiles ${Dotfiles}.bak
sudo rm -rf $Dotfiles

# Make the folders inside the dotfiles folder
mkdir $Dotfiles
mkdir $Dotfiles/.config
mkdir $Dotfiles/.scripts
mkdir $Dotfiles/Wallpapers

# Copy dotfolders into the new dotfiles directory
sudo cp -a ~/.config/polybar $Dotfiles/.config/
sudo cp -a ~/.config/rofi $Dotfiles/.config/
sudo cp -a ~/.config/i3 $Dotfiles/.config/
sudo cp -a ~/.config/picom $Dotfiles/.config/
sudo cp -a ~/.scripts/* $Dotfiles/.scripts/
sudo cp -a ~/Wallpapers/* $Dotfiles/Wallpapers/
sudo cp ~/.bash_profile $Dotfiles/
sudo cp ~/.bashrc $Dotfiles/
sudo cp ~/.xinitrc $Dotfiles/


# Done proccess
echo dotfiles packed at $Dotfiles
